config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users

  namespace :admins do
    resources :users, only: [:index, :show] 
  end

  scope module: 'public' do
    root "homes#top"
    get "search" => "searches#search"

    resources :post_images, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scentopia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/f35d0831d9.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

      <nav class="navbar navbar-expand-lg navbar-dark bs-dark border-bottom border-info">

      <% if user_signed_in? %>
        <div class="container">
        <strong>
          <%= link_to "Scentopia", post_images_path, class: "navbar-brand text-info" %>
        </strong>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <%= render 'public/searches/search' %>

              <li class="nav-link text-info">
                <%= link_to '投稿', new_post_image_path, class: "text-info" %>
                <i class="fa-solid fa-plus"></i>
              </li>
              <li class="nav-link text-info">
                <%= link_to 'マイページ', user_path(current_user.id), class: "text-info" %>
                <i class="fa-regular fa-user"></i>
              </li>
              <li class="nav-link text-info">
                <%= link_to "いいね", likes_user_path(current_user.id), class: "text-info" %>
                <i class="fa-regular fa-heart"></i>
              </li>
              <li class="nav-link text-info">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-info" %>
                <i class="fa-solid fa-arrow-right-from-bracket"></i>
              </li>
            </ul>
          </div>
        </div>
        <% elsif admin_user_signed_in? %>
          <strong>
            <%= link_to "Scentopia", root_path, class: "navbar-brand text-info" %>
          </strong>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-link text-info">
                <%= link_to "会員一覧", admins_users_path, class: "text-info" %>
                <i class="fa-regular fa-user"></i>
              </li>
              <li class="nav-link text-info">
                <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "text-info" %>
                <i class="fa-solid fa-arrow-right-from-bracket"></i>
              </li>
            </ul>
          </div>
      <% else %>
        <div class="container">
        <strong>
          <%= link_to "Scentopia", root_path, class: "navbar-brand text-info" %>
        </strong>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-link text-info">
                <%= link_to "新規登録", new_user_registration_path, class: "text-info" %>
                <i class="fa-solid fa-pen-to-square"></i>
              </li>
              <li class="nav-link text-info">
                <%= link_to "ログイン", new_user_session_path, class: "text-info" %>
                <i class="fa-solid fa-arrow-right-to-bracket"></i>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
      </nav>


    </header>


    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>